import{a as m,S as h,i as l}from"./assets/vendor-09d7c26e.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))o(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const c of r.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&o(c)}).observe(document,{childList:!0,subtree:!0});function n(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function o(e){if(e.ep)return;e.ep=!0;const r=n(e);fetch(e.href,r)}})();const y="43943872-0cd26c97fed3a84845e31fcef";function g(t,s){return m.get(`https://pixabay.com/api/?key=${y}&q=${t}&image_type=photo&orientation=horizontal&safesearch=true&page=${s}&per_page=15`).then(n=>n.data.hits).catch(n=>console.error(n))}function L(t,s){if(t.length===0){iziToast.error({title:"Error",message:"Изображения, соответствующие вашему запросу, не найдены. Пожалуйста, попробуйте еще раз."});return}const n=t.map(o=>`
      <li class="image-card">
  <a href="${o.largeImageURL}"><img src="${o.webformatURL}" alt="${o.tags}" title="" style="height:150px; width:150px;"/></a>
  <div class="image-info">
    <p><span>Просмотры: </span>${o.views}</p>
    <p><span>Загрузки: </span>${o.downloads}</p>
    <p><span>Лайки: </span>${o.likes}</p>
    <p><span>Комментарии: </span>${o.comments}</p>
  </div>
</li>
  `).join("");s.innerHTML+=n}const v=document.querySelector("#search-form"),$=document.querySelector("#search-input"),u=document.querySelector("#gallery"),d=document.querySelector("#loader"),i=document.querySelector("#load-more");let p=1,a="";v.addEventListener("submit",t=>{if(t.preventDefault(),a=$.value.trim(),!a){alert("Пожалуйста, введите ключевое слово для поиска");return}p=1,u.innerHTML="",f()});i.addEventListener("click",f);function f(){d.classList.remove("hidden"),g(a,p++).then(t=>{console.log(t),d.classList.add("hidden"),L(t,u),new h(".image-card a",{}),t.length===15?i.style.display="block":(i.style.display="none",l.info({title:"Info",message:"We're sorry, but you've reached the end of search results."}))}).catch(t=>{console.error(t),l.error({title:"Error",message:"Произошла ошибка при загрузке изображений. Пожалуйста, попробуйте еще раз."})}),scrollToNextPage()}
//# sourceMappingURL=commonHelpers.js.map
