import{a as h,i as c,S as g}from"./assets/vendor-09d7c26e.js";(function(){const n=document.createElement("link").relList;if(n&&n.supports&&n.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))o(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const a of r.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&o(a)}).observe(document,{childList:!0,subtree:!0});function s(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function o(e){if(e.ep)return;e.ep=!0;const r=s(e);fetch(e.href,r)}})();const y="43943872-0cd26c97fed3a84845e31fcef";function L(t,n){return h.get(`https://pixabay.com/api/?key=${y}&q=${t}&image_type=photo&orientation=horizontal&safesearch=true&page=${n}&per_page=15`).then(s=>s.data.hits).catch(s=>console.error(s))}function v(t,n){if(t.length===0){iziToast.error({title:"Error",message:"Изображения, соответствующие вашему запросу, не найдены. Пожалуйста, попробуйте еще раз."});return}const s=t.map(o=>`
      <li class="image-card">
  <a href="${o.largeImageURL}"><img src="${o.webformatURL}" alt="${o.tags}" title="" style="height:150px; width:150px;"/></a>
  <div class="image-info">
    <p><span>Просмотры: </span>${o.views}</p>
    <p><span>Загрузки: </span>${o.downloads}</p>
    <p><span>Лайки: </span>${o.likes}</p>
    <p><span>Комментарии: </span>${o.comments}</p>
  </div>
</li>
  `).join("");n.innerHTML+=s}function $(){const n=document.querySelector(".image-card").getBoundingClientRect().height;window.scrollBy({top:n*2,behavior:"smooth"})}const b=document.querySelector("#search-form"),d=document.querySelector("#search-input"),p=document.querySelector("#gallery"),u=document.querySelector("#loader"),i=document.querySelector("#load-more");let f=1,l="";b.addEventListener("submit",t=>{if(t.preventDefault(),l=d.value.trim(),!l){c.warning({title:"Warning",message:"Пожалуйста, введите ключевое слово для поиска"});return}f=1,p.innerHTML="",m(),d.value=""});i.addEventListener("click",m);function m(){i.style.display="none",u.classList.remove("hidden"),L(l,f++).then(t=>{u.classList.add("hidden"),v(t,p),new g(".image-card a",{}),t.length===15?i.style.display="block":(i.style.display="none",c.info({title:"Info",message:"We're sorry, but you've reached the end of search results."})),$()}).catch(t=>{c.error({title:"Error",message:"Произошла ошибка при загрузке изображений. Пожалуйста, попробуйте еще раз."})})}
//# sourceMappingURL=commonHelpers.js.map
